title: Pierre Blanche
author: Jerome David
favicon: favicon.svg
timezone: Europe/Paris

collections:
  posts:
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
      permalink: /:path/:basename
  -
    scope:
      path: "club.md"
      type: pages
    values:
      layout: club
      permalink: /:path/:basename
  -
    scope:
      path: "falaise.md"
      type: pages
    values:
      layout: falaise
      permalink: /:path/:basename
